# -*- coding: utf-8 -*-
"""prg2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w19MbRlo2_uAhvgE9BF2TKMgGf6D8yio
"""

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
add_result=np.add(a,b)
print("Addition:",add_result)
sub_result=np.subtract(a,b)
print("Substraction:",sub_result)
mul_result=np.multiply(a,b)
print("Multiplication:",mul_result)
div_result=np.divide(a,b)
print("Division:",div_result)